### ISSUE TITLE
请问如何在docker里面运行cron？

### ISSUE THREAD

**Issue by chinobing** [0604hx/buter#1]
请问一下使用Flask-APScheduler创建了cron的定时任务后，如何在docker里面运行，我的flask用docker-compose up运行后，发现APScheduler不会启动？

**Comment by 18611196340** [comment]
由于基础镜像中没有crontab服务，需要在打包自己镜像的Dockerfile中加入安装cron服务的步骤。

FROM python:3.6-slim
MAINTAINER whx3000 <wanghaoxi3000@163.com>

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    cron && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN chmod +x ./docker-entrypoint.sh

ENV LC_ALL C.UTF-8
ENTRYPOINT ["./docker-entrypoint.sh"]
执行apt安装时注意加入-y --no-install-recommends，并且在安装完成后执行rm -rf /var/lib/apt/lists/* && apt-get clean命令，可以有效减小镜像的体积。

这样安装完cron服务后，crontab服务并不会自启动，还需要一个docker-entrypoint.sh启动脚本来添加crontab的启动命令。

启动脚本
#!/bin/bash
set -x

# 保存环境变量，开启crontab服务
env >> /etc/default/locale
/etc/init.d/cron start
/etc/init.d/cron start用于启动crontab服务，但这样启动的crontab服务中配置的定时命令是没有Dockerfile中设置的环境变量的。因此还需要在这之前执行env >> /etc/default/locale，这样有Dockerfile中通过ENV设置的环境变量在crontab中就可以正常读取了。

##########----------------------------------------------###########
实际上我也没用过，上边是百度搜的，我是你的粉丝，追到了GitHub哈哈

**Comment by chinobing** [comment]
谢啦。现在没有用docker了，直接就在vps上安装。。话说粉丝什么的是神马情况
